@startuml draftUC

left to right direction
actor Teknisi as T
actor Supervisor as Spv 
actor "<<System>>" as Sys
actor "Super Admin" as SA

package "Dashboard" {
    ' Teknisi
    usecase "Lihat daftar komponen PLC bermasalah\nsesuai plant yang ditugaskan" as UC1
    usecase "Perbarui progress\nmaintenance" as UC2

    ' Supervisor
    usecase "Pantau kondisi plant yang ditugaskan" as UC3
    usecase "Jalankan job sinkronisasi\ndata secara manual" as UC4
    usecase "Lihat seluruh data komponen PLC\ndi plant yang ditugaskan" as UC5
    usecase "Lihat dan unduh laporan\nprogress maintenance" as UC6

    ' Sistem
    usecase "Jalankan sinkronisasi data\notomatis via task scheduler" as UC7
    usecase "Kirim notifikasi email jika ada\nkomponen berstatus DANGER" as UC8

    ' Super Admin
    usecase "Buat akun pengguna" as UC9
    usecase "Kelola hak akses pengguna" as UC10
    usecase "Kelola token akses API" as UC11
}

SA --> UC9
SA --> UC10
SA --> UC11

T --> UC1
UC1 ..> UC2 : <<include>>

Spv --> UC3
Spv --> UC4
UC3 ..> UC5 : <<include>>
UC3 ..> UC6 : <<include>>
UC4 <.. UC8 : <<extend>>

Sys --> UC7
UC7 <.. UC8 : <<extend>>

@enduml